apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::606710963608:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1L7Y088O1XBN0
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::606710963608:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2023-04-23T11:11:41Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1738"
  uid: 4a82effd-4d92-40d4-aea4-f93fad060164
